### ISSUE TITLE
关于 phpredisConnector.php 的疑问

### ISSUE THREAD

**Issue by miaotiao** [immortalChensm/laravel5.8#2]
大兄弟，framework\src\Illuminate\Redis\Connectors\PhpRedisConnector.php->createClient 的三行代码怎么让你给删除了呢？
![image](https://user-images.githubusercontent.com/28383349/70308171-aa77a800-1845-11ea-8f0c-6f3a3f3e6a6c.png)

**Comment by immortalChensm** [comment]
redis的管理由RedisManager管理器负责【注册在容器中Container类里，http请求时就注册了，每请求一次就跑一次】使用时【读取config/database】 
【 $config = $app->make('config')->get('database.redis', []);】因为框架在启动时【HTTP请求之时】这个管理器早就保存在数组里了【专业点叫服务注册】，它呢有2个phpredis/predis 
Connectors\PhpRedisConnector 它使用的是Redis类【安装好扩展后就可以用了】 
而Connectors\PredisConnector 使用的是Predis\Client类【这个类的扩展我没有装，所以为了测试就注释掉了】 

它们都只是封装了redis[redis client api]而已，一样的使用【底层仍然是tcp传输redis指令获取服务器的数据返回，所以可以去拿官方的API直接用都可以的】
